apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
 # storageClassName: techxper-azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:    
      storage: 2Gi

      