apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tx-clusterissuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sunandad2090@gmail.com
    privateKeySecretRef:
      name: techxper-secret
    solvers:
    - http01:
        ingress:
          class: nginx
